include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    always_declare_return_types: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true
    use_super_parameters: true
    sort_child_properties_last: true
